# Codemagic build configuration for Fitlyf Android app
workflows:
  android-build:
    name: Android Build
    instance_type: mac_mini_m1 # Use the free Mac Mini machine
    environment:
      flutter: stable
      java: 17        # We still declare Java 17 here
    scripts:
      # THIS IS THE FIX: This command forces the machine to use the Java 17 path.
      - export JAVA_HOME=$(/usr/libexec/java_home -v 17)
      - flutter packages pub get
      - flutter analyze
      - flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - your.email@example.com # Optional: Add your email
