# Codemagic build configuration for Fitlyf Android app
workflows:
  android-build:
    name: Android Build
    # THIS IS THE FIX: We are now using the free Mac Mini machine.
    instance_type: mac_mini_m1
    environment:
      flutter: stable # Using stable is often better than a fixed version
      java: 17        # We still need Java 17, even on a Mac, for Android builds.
    scripts:
      - flutter packages pub get
      - flutter analyze
      - flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - your.email@example.com # Optional: Add your email to get the build file
