workflows:
  android-build-free-tier:
    name: Android Build (Free Tier)
    instance_type: mac_mini_m1
    environment:
      flutter: 3.19.6 # Using a known stable version
      xcode: 15.2
      java: 17
      # THE FIX (Layer 2): Force the Java Virtual Machine to use more memory
      # This is a powerful override for the entire build environment.
      _JAVA_OPTIONS: "-Xms1g -Xmx4g" 
    scripts:
      # These scripts are now much cleaner
      - flutter clean
      - flutter pub get
      - flutter build apk --debug
    artifacts:
      - build/app/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - your.email@example.com
