workflows:
  android-build-free-tier:
    name: Android Build (Free Tier)
    instance_type: mac_mini_m1
    environment:
      flutter: 3.19.6
      xcode: 15.2
      java: 17
    scripts:
      - echo "JAVA_HOME=$(/usr/libexec/java_home -v 17)" >> $CM_ENV
      - export JAVA_HOME=$(/usr/libexec/java_home -v 17)
      - java -version
      - flutter --version
      - flutter pub get
      - flutter clean # <-- THE FIX: Ensures a clean build every time.
      - cd android && ./gradlew clean && cd ..
      - flutter build apk --debug
    artifacts:
      - build/app/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - your.email@example.com
