# Codemagic build configuration for Fitlyf Android app
workflows:
  android-build:
    name: Android Build
    instance_type: mac_mini_m1 # Use the free Mac Mini machine
    environment:
      flutter: 3.19.6 # Pinned to a known stable version
      xcode: 15.2
      java: 17
    scripts:
      # --- SETUP AND VERIFICATION ---
      # Force Java 17 and verify its version in the logs.
      - export JAVA_HOME=$(/usr/libexec/java_home -v 17)
      - java -version
      
      # --- AGGRESSIVE CLEANING STEPS ---
      # 1. Clean all Flutter build artifacts.
      - echo "--- CLEANING FLUTTER PROJECT ---"
      - flutter clean
      
      # 2. Get the project dependencies.
      - flutter packages pub get
      
      # 3. THIS IS THE NEW FIX: Force the Android Gradle wrapper to clean itself.
      - echo "--- CLEANING GRADLE PROJECT ---"
      - cd android && ./gradlew clean && cd ..

      # --- BUILD STEP ---
      - echo "--- STARTING BUILD ---"
      - flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - your.email@example.com # Optional: Add your email
