name: fitlyf
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # For state management
  provider: ^6.1.2

  # For date formatting (like 'EEEE' for Monday)
  intl: ^0.19.0

  # THE NEW DEPENDENCY for creating beautiful charts
  fl_chart: ^0.68.0

  # The default icon pack
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # For code analysis and linting
  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
