name: fitlyf
description: Your personal fitness and lifestyle tracker.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^6.1.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  fl_chart: ^0.66.2
  cupertino_icons: ^1.0.2
  image_picker: ^1.1.2
  video_player: ^2.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
