name: fitlyf
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  intl: ^0.19.0 
  fl_chart: ^0.68.0 # <-- ADD THIS LINE FOR THE CHARTS

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
