name: fitlyf
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  image_picker: ^1.0.7
  firebase_storage: ^11.6.0
  intl: ^0.19.0
  table_calendar: ^3.0.9
  fl_chart: ^0.68.0
  google_fonts: ^6.2.1
  
  # THE FIX: This line is required to play videos.
  video_player: ^2.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
